-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.28-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.5.0.6677
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table ddrsistemas.products: ~23 rows (approximately)
INSERT INTO `products` (`id`, `name`, `slug`, `details`, `price`, `shipping_cost`, `description`, `category_id`, `brand_id`, `image_path`, `created_at`, `updated_at`) VALUES
	(1, 'GinecoReport', 'GINECOLOGÍA', 'Lleve el control pre-natal, imprima el reporte de exámenes especializados como ecos y colposcopias, emita con comodidad recetas, constancias, informes médicos, etc.', 24.99, 2.99, 'Lleve el control pre-natal, imprima el reporte de exámenes especializados como ecos y colposcopias, emita con comodidad recetas, constancias, informes médicos, etc.', 1, 1, 'GinecoReport', '2023-10-14 05:58:50', '2023-10-14 05:58:50'),
	(12, 'PediaReport', 'PEDIATRÍA', 'En la consulta pediátrica se requiere un seguimiento particular, PediaReport integra funcionalidad para el monitoreo de la curva de crecimiento y la elaboración de reportes especializados.', 0, 0, 'En la consulta pediátrica se requiere un seguimiento particular, PediaReport integra funcionalidad para el monitoreo de la curva de crecimiento y la elaboración de reportes especializados.', 1, 1, 'PediaReport', NULL, NULL),
	(13, 'CardioReport', 'CARDIOLOGÍA', 'Genere y manipule gráficas e indicadores, imprima revisiones pre-operatorias, resultados de ecografías, récipes, constancias, referencias, informes médicos, etc.', 0, 0, 'Genere y manipule gráficas e indicadores, imprima revisiones pre-operatorias, resultados de ecografías, récipes, constancias, referencias, informes médicos, etc.', 1, 1, 'CardioReport', NULL, NULL),
	(14, 'DermaReport', 'DERMATOLOGÍA', 'Imprima recetas, informes médicos, visualice y compare las imágenes de sus pacientes. Lleve el control de las intervenciones quirúrgicas y centralice la gestión de las historias clínicas', 0, 0, 'Imprima recetas, informes médicos, visualice y compare las imágenes de sus pacientes. Lleve el control de las intervenciones quirúrgicas y centralice la gestión de las historias clínicas', 1, 1, 'DermaReport', NULL, NULL),
	(15, 'EcoReport', 'ECOGRAFÍA', 'Incorpore a sus reportes todos los formatos que produzca el ultrasonido, maneje las citas, genere estadísticas y ejecute tareas de administración propias de la operación del consultorio.', 0, 0, 'Incorpore a sus reportes todos los formatos que produzca el ultrasonido, maneje las citas, genere estadísticas y ejecute tareas de administración propias de la operación del consultorio.', 1, 1, 'EcoReport', NULL, NULL),
	(16, 'EstheticReport', 'MEDICINA ESTÉTICA', 'Controle tratamientos de láser, peeling, bótox, elabore la ficha facial, etc. Imprima los consentimientos informados, recetas, constancias, reposos, presupuestos, etc.', 0, 0, 'Controle tratamientos de láser, peeling, bótox, elabore la ficha facial, etc. Imprima los consentimientos informados, recetas, constancias, reposos, presupuestos, etc.', 1, 1, 'EstheticReport', NULL, NULL),
	(17, 'GastroReport', 'GASTROENTEROLOGÍA', 'Imprima con sus imágenes los formatos de la endoscopia digestiva superior e inferior; emita fácilmente recetas, constancias, informes médicos, etc. Optimice la operación de su consultorio.', 0, 0, 'Imprima con sus imágenes los formatos de la endoscopia digestiva superior e inferior; emita fácilmente recetas, constancias, informes médicos, etc. Optimice la operación de su consultorio.', 1, 1, 'GastroReport', NULL, NULL),
	(18, 'MedicReport', 'MEDICINA INTERNA', 'Genere gráficas de indicadores, maneje la información de cada paciente, imprima evaluaciones pre-operatorias, recetas, constancias, informes médicos, etc.', 0, 0, 'Genere gráficas de indicadores, maneje la información de cada paciente, imprima evaluaciones pre-operatorias, recetas, constancias, informes médicos, etc.', 1, 1, 'MedicReport', NULL, NULL),
	(19, 'NefroReport', 'NEFROLOGÍA', 'Cargue los resultados de exámenes, genere fórmulas, gráficas y relaciones. Emita con comodidad recetas, reposos, referencias, facturas,presupuestos, informes, etc.', 0, 0, 'Cargue los resultados de exámenes, genere fórmulas, gráficas y relaciones. Emita con comodidad recetas, reposos, referencias, facturas,presupuestos, informes, etc.', 1, 1, 'NefroReport', NULL, NULL),
	(20, 'NeumoReport', 'NEUMONOLOGÍA', 'Imprima evaluaciones pre-operatorias, recetas, constancias, informes médicos, resultados de exámenes especializados como la espirometría. Tome el control del desempeño de su consultorio.', 0, 0, 'Imprima evaluaciones pre-operatorias, recetas, constancias, informes médicos, resultados de exámenes especializados como la espirometría. Tome el control del desempeño de su consultorio.', 1, 1, 'NeumoReport', NULL, NULL),
	(21, 'NeuroReport', 'NEUROCIRUGÍA', 'Genere informes de presupuestos, recetas, reposos, constancias, referencias, informes médicos. Lleve la administración de su práctica profesional, compile estadísticas de desempeño, etc.', 0, 0, 'Genere informes de presupuestos, recetas, reposos, constancias, referencias, informes médicos. Lleve la administración de su práctica profesional, compile estadísticas de desempeño, etc.', 1, 1, 'NeuroReport', NULL, NULL),
	(22, 'NutriReport', 'NUTRICIÓN Y DIETÉTICA', 'El aliado perfecto para el nutricionista, controle la alimentación del paciente y haga seguimiento práctico a la evolución de cada tratamiento.', 0, 0, 'El aliado perfecto para el nutricionista, controle la alimentación del paciente y haga seguimiento práctico a la evolución de cada tratamiento.', 1, 1, 'NutriReport', NULL, NULL),
	(23, 'OdontoReport', 'ODONTOLOGÍA', 'Digitalice el odontodiagrama de sus pacientes; registre presupuestos, imágenes, citas, recetas, reposos, constancias, informes, etc. e intégrelos con facilidad a la ficha personal de cada suj', 0, 0, 'Digitalice el odontodiagrama de sus pacientes; registre presupuestos, imágenes, citas, recetas, reposos, constancias, informes, etc. e intégrelos con facilidad a la ficha personal de cada suj', 1, 1, 'OdontoReport', NULL, NULL),
	(24, 'OftalReport', 'OFTALMOLOGÍA', 'De manera intuitiva genere y almacene informes de cataratas, estrabismo u otras condiciones oftalmológicas, emita rápidamente fórmulas ópticas, récipes, constancias u otros formatos requerido', 0, 0, 'De manera intuitiva genere y almacene informes de cataratas, estrabismo u otras condiciones oftalmológicas, emita rápidamente fórmulas ópticas, récipes, constancias u otros formatos requerido', 1, 1, 'OftalReport', NULL, NULL),
	(25, 'OncoReport', 'ONCOLOGÍA', 'Provee funcionalidad para darle cobertura a cada detalle en el seguimiento de un caso en esta especialidad, desde la fase diagnóstica hasta el post-operatorio.', 0, 0, 'Provee funcionalidad para darle cobertura a cada detalle en el seguimiento de un caso en esta especialidad, desde la fase diagnóstica hasta el post-operatorio.', 1, 1, 'OncoReport', NULL, NULL),
	(26, 'ORLReport', 'OTORRINOLARINGOLOGÍA', 'Almacena y provee una rápida visualización para resultados de varios estudios especializados, habilita al profesional para la cómoda emisión de diversos formatos médicos,', 0, 0, 'Almacena y provee una rápida visualización para resultados de varios estudios especializados, habilita al profesional para la cómoda emisión de diversos formatos médicos,', 1, 1, 'ORLReport', NULL, NULL),
	(27, 'OrthoReport', 'TRAUMATOLOGÍA', 'Genere presupuestos y monitoree la evolución de los pagos, realice solicitudes para implantes o de servicios para intervención. Gestione eficientemente las historias clínicas de sus pacientes', 0, 0, 'Genere presupuestos y monitoree la evolución de los pagos, realice solicitudes para implantes o de servicios para intervención. Gestione eficientemente las historias clínicas de sus pacientes', 1, 1, 'OrthoReport', NULL, NULL),
	(28, 'PlasticReport', 'CIRUGÍA PLÁSTICA', 'Visualice y compare las imágenes para evaluar el progreso de cada tratamiento, incorpórelas a sus informes para mejorar la presentación de los mismos. Lleve el control de las intervenciones q', 0, 0, 'Visualice y compare las imágenes para evaluar el progreso de cada tratamiento, incorpórelas a sus informes para mejorar la presentación de los mismos. Lleve el control de las intervenciones q', 1, 1, 'PlasticReport', NULL, NULL),
	(30, 'SurgeryReport', 'CIRUGÍA GENERAL', 'Registre de forma ordenada la información relativa a cada intervención, imprima recetas, reposos, constancias, referencias, informes médicos, etc. Haga un óptimo seguimiento a cada caso.', 0, 0, 'Registre de forma ordenada la información relativa a cada intervención, imprima recetas, reposos, constancias, referencias, informes médicos, etc. Haga un óptimo seguimiento a cada caso.', 1, 1, 'SurgeryReport', NULL, NULL),
	(31, 'UroloReport', 'UROLOGÍA', 'Elabore y emita rápidamente todo tipo de formatos, incorporándole el refuerzo visual de la imagenología. Organice su flujo de trabajo y optimice de su desempeño económico.', 0, 0, 'Elabore y emita rápidamente todo tipo de formatos, incorporándole el refuerzo visual de la imagenología. Organice su flujo de trabajo y optimice de su desempeño económico.', 1, 1, 'UroloReport', NULL, NULL),
	(32, 'ActualizaReport', 'Actualización del Sistema', 'Actualicé su Softwara para Mayor Seguridad', 0, 0, 'Actualicé su Softwara para Mayor Seguridad', 1, 1, 'ActualizaReport', NULL, NULL),
	(33, 'NubeReport', 'Respaldo en la Nube', 'Respalde su Informacion en la Nube', 0, 0, 'Respalde su Informacion en la Nube', 1, 1, 'NubeReport', NULL, NULL),
	(34, 'SoporteReport', 'Soporte Técnico', 'Dirigido a clientes cuya dinámica requiere contar con el apoyo de nuestro equipo de soporte técnico, para resolver al momento cualquier inconveniente y sacar el máximo provecho a nuestros sis', 0, 0, 'Dirigido a clientes cuya dinámica requiere contar con el apoyo de nuestro equipo de soporte técnico, para resolver al momento cualquier inconveniente y sacar el máximo provecho a nuestros sis', 1, 1, 'SoporteReport', NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
